// This is free and unencumbered software released into the public domain.
// For more information, please refer to <http://unlicense.org/>

#ifndef OTLS_SPANANALYZER_ANALYSISCONTROLLER_H_
#define OTLS_SPANANALYZER_ANALYSISCONTROLLER_H_

#include <vector>

#include "models/sagtension/line_cable_reloader.h"

#include "sag_tension_analysis_results.h"
#include "span.h"

/// \par OVERVIEW
///
/// This class handles the sag-tension analysis and generates cached data
/// for the application to display.
///
/// \par RESULTS
///
/// This class uses a reloader from the OTLS-Models calculation library to
/// generate the results.
///
/// This class does not update the results automatically. Results can only be
/// generated by using the RunAnalysis() method. This is done because:
///  - a span is not always selected
///  - results are computationally expensive and need to be calculated only as
///    needed
class AnalysisController {
 public:
  /// \brief Constructor.
  AnalysisController();

  /// \brief Destructor.
  ~AnalysisController();

  /// \brief Clears the sag-tension results.
  void ClearResults();

  /// \brief Gets the sag-tension analyis result.
  /// \param[in] index_weathercase
  ///   The weathercase index.
  /// \param[in] condition
  ///   The condition.
  /// \return The sag-tension analysis result. If the index did not match up to
  ///   the results list, a nullptr is returned.
  const SagTensionAnalysisResult* Result(
      const int& index_weathercase,
      const CableConditionType& condition) const;

  /// \brief Gets the sag-tension analysis results.
  /// \param[in] condition
  ///   The condition.
  /// \return The sag-tension analysis results.
  const std::vector<SagTensionAnalysisResult>* Results(
      const CableConditionType& condition) const;

  /// \brief Runs the sag-tension analysis.
  void RunAnalysis() const;

  /// \brief Gets the analysis stretch state for the specified condition.
  /// \param[in] condition
  ///   The condition.
  /// \return The stretch state for the specified condition. If no stretch
  ///   state is available, a nullptr is returned.
  const CableStretchState* StretchState(const CableConditionType& condition);

  /// \brief Sets the activated span.
  /// \param[in] span
  ///   The span.
  void set_span(const Span* span);

  /// \brief Sets the weathercases.
  /// \param[in] weathercases
  ///   The reference data.
  void set_weathercases(const std::list<WeatherLoadCase*>* weathercases);

  /// \brief Gets the span.
  /// \return The span. If no span is set, a nullptr is returned.
  const Span* span() const;

  /// \brief Gets the weathercases.
  /// \return The weathercases.
  const std::list<WeatherLoadCase*>* weathercases() const;

 private:
  /// \brief Analyzes a weathercase.
  /// \param[in] weathercase
  ///   The weathercase.
  /// \param[in] condition
  ///   The cable condition.
  /// \return A sag-tension analysis result.
  SagTensionAnalysisResult Analyze(const WeatherLoadCase& weathercase,
                                   const CableConditionType& condition) const;

  /// \var reloader_
  ///   The line cable reloader. This solves for the sag-tension results. When
  ///   not running an analysis, this is set to an invalid state.
  mutable LineCableReloader reloader_;

  /// \var results_creep_
  ///   The analysis results for the creep condition.
  mutable std::vector<SagTensionAnalysisResult> results_creep_;

  /// \var results_initial_
  ///   The analysis results for the initial condition.
  mutable std::vector<SagTensionAnalysisResult> results_initial_;

  /// \var results_load_
  ///   The analysis results for the load condition.
  mutable std::vector<SagTensionAnalysisResult> results_load_;

  /// \var span_
  ///   The span being analyzed.
  const Span* span_;

  /// \var state_stretch_creep_
  ///   The calculated stretch state for the creep condition.
  mutable CableStretchState state_stretch_creep_;

  /// \var state_stretch_initial_
  ///   The stretch state for the initial condition.
  CableStretchState state_stretch_initial_;

  /// \var state_stretch_load_
  ///   The calculated stretch state for the load condition.
  mutable CableStretchState state_stretch_load_;

  /// \var weathercases_
  ///   The weathercases to be analyzed.
  const std::list<WeatherLoadCase*>* weathercases_;
};

#endif  // OTLS_SPANANALYZER_ANALYSISCONTROLLER_H_
